import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;

@WebServlet("/Currency")
public class Currency extends HttpServlet {
    private static final long serialVersionUID = 1L;

    // Map to store exchange rates dynamically
    private Map<String, Map<String, Double>> exchangeRates = new HashMap<>();

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        
        double amount;
        String fromCurrency = request.getParameter("from-currency");
        String toCurrency = request.getParameter("to-currency");
        
        

        // Validate amount
        try {
            amount = Double.parseDouble(request.getParameter("amount"));
        } catch (NumberFormatException e) {
            response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Invalid amount format");
            return;
        }

        double result = converted_currency(amount, fromCurrency, toCurrency);
        if (result == -1) {
            response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Conversion rate not available for the given currencies");
            return;
        }

        out.println("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        out.println("<title>Currency Converter Result</title>");
        out.println("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"></head>");
        out.println("<body class=\"bg-gray-100 min-vh-100 d-flex align-items-center justify-content-center\">");
        out.println("<div class=\"bg-white p-4 rounded-lg shadow-md w-50\" style=\"border: 3px solid black;\">");
        out.println("<h2 class=\"text-3xl font-semibold mb-4\">Result:</h2>");
        out.println("<p style=\"font-size: 24px;\"><span style=\"color: red;\">" + amount + "</span> " + fromCurrency + " is equal to <span style=\"color: red;\">" + String.format("%.4f", result) + "</span> " + toCurrency + "</p>");
        out.println("<style>.btn-custom { background-color: black; color: white; transition: transform 0.3s ease; }.btn-custom:hover { transform: scale(1.03); background-color: black; color: white;}</style>");
        out.println("<a href=\"index.jsp\" class=\"btn btn-custom mt-4\">Back</a>");
        out.println("</div>");
        out.println("</body></html>");
        
     // JDBC connection variables
        try 
        		
        		{
        	try {
				Class.forName("com.mysql.jdbc.Driver");
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    		
    		Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/movies", "root", "root") ;
            // Create SQL insert statement
            String sql = "INSERT INTO currency_converter(amount, from_currency, to_currency, generated_at) VALUES (?, ?, ?, ?)";
            
            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                // Prepare statement
                preparedStatement.setDouble(1, amount);
                preparedStatement.setString(2, fromCurrency);
                preparedStatement.setString(3, toCurrency);
                preparedStatement.setTimestamp(4, new Timestamp(System.currentTimeMillis())); // current timestamp

                // Execute insert query
                preparedStatement.executeUpdate();
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        request.setAttribute("amount",amount);
		request.setAttribute("from-currency",fromCurrency);
		request.setAttribute("to-currency",toCurrency);
		
//		request.getRequestDispatcher("index.jsp").forward(request, response);
    }

    private double converted_currency(double amount, String fromCurrency, String toCurrency) {
        populate_exchangeRates();

        // If from and to currencies are the same, return the amount unchanged
        if (fromCurrency.equals(toCurrency)) {
            return amount;
        }

        if (fromCurrency.equals("INR")) {
            // Converting from INR to another currency
            return amount / exchangeRates.get(toCurrency).get("INR");
        } else if (toCurrency.equals("INR")) {
            // Converting to INR from another currency
            return amount * exchangeRates.get(fromCurrency).get("INR");
        } else {
            // Perform conversion if both currencies are not INR
            Double exchangeRate = exchangeRates
                    .getOrDefault(fromCurrency, new HashMap<>())
                    .get(toCurrency);
            if (exchangeRate != null) {
                return amount * exchangeRate;
            } else {
                return -1; // Unsupported conversion
            }
        }
    }


	private void populate_exchangeRates() {
	    // USD to other currencies
	    Map<String, Double> usdRates = new HashMap<>();
	    usdRates.put("INR", 83.95);
	    usdRates.put("EUR", 0.91);
	    usdRates.put("GBP", 0.77);
	    usdRates.put("JPY", 146.78);
	    usdRates.put("AUD", 1.50);
	    usdRates.put("CAD", 1.34);
	    usdRates.put("CNY", 7.29);
	    usdRates.put("RUB", 93.68);
	    usdRates.put("BRL", 4.91);
	    usdRates.put("MXN", 17.11);
	    usdRates.put("ZAR", 18.66);
	    usdRates.put("SAR", 3.75);
	    usdRates.put("KRW", 1321.05);
	    usdRates.put("CHF", 0.88);
	    usdRates.put("TRY", 26.96);
	    usdRates.put("SGD", 1.36);
	    usdRates.put("NZD", 1.62);
	    usdRates.put("SEK", 11.01);
	    usdRates.put("NOK", 10.61);
	    usdRates.put("DKK", 6.78);
	    usdRates.put("MYR", 4.61);
	    usdRates.put("THB", 35.27);
	    usdRates.put("IDR", 15343.75);
	    usdRates.put("PHP", 56.79);
	    usdRates.put("NGN", 774.50);
	    usdRates.put("EGP", 30.91);
	    usdRates.put("ARS", 347.75);
	    usdRates.put("CLP", 872.45);
	    usdRates.put("VND", 24140.00);
	    usdRates.put("PKR", 283.23);
	    usdRates.put("BDT", 108.47);
	    usdRates.put("AED", 3.67);
	    usdRates.put("QAR", 3.64);
	    usdRates.put("ILS", 3.75);
	    exchangeRates.put("USD", usdRates);

	    // INR to other currencies
	    Map<String, Double> inrRates = new HashMap<>();
	    inrRates.put("USD", 0.012);
	    inrRates.put("EUR", 0.011);
	    inrRates.put("GBP", 0.0096);
	    inrRates.put("JPY", 1.75);
	    inrRates.put("AUD", 0.019);
	    inrRates.put("CAD", 0.016);
	    inrRates.put("CNY", 0.087);
	    inrRates.put("RUB", 1.12);
	    inrRates.put("BRL", 0.059);
	    inrRates.put("MXN", 0.20);
	    inrRates.put("ZAR", 0.22);
	    inrRates.put("SAR", 0.045);
	    inrRates.put("KRW", 15.73);
	    inrRates.put("CHF", 0.010);
	    inrRates.put("TRY", 0.32);
	    inrRates.put("SGD", 0.016);
	    inrRates.put("NZD", 0.019);
	    inrRates.put("SEK", 0.13);
	    inrRates.put("NOK", 0.13);
	    inrRates.put("DKK", 0.081);
	    inrRates.put("MYR", 0.055);
	    inrRates.put("THB", 0.42);
	    inrRates.put("IDR", 182.75);
	    inrRates.put("PHP", 0.68);
	    inrRates.put("NGN", 9.23);
	    inrRates.put("EGP", 0.37);
	    inrRates.put("ARS", 4.14);
	    inrRates.put("CLP", 10.39);
	    inrRates.put("VND", 287.81);
	    inrRates.put("PKR", 3.31);
	    inrRates.put("BDT", 1.29);
	    inrRates.put("AED", 0.044);
	    inrRates.put("QAR", 0.044);
	    inrRates.put("ILS", 0.045);
	    exchangeRates.put("INR", inrRates);

	    // EUR to other currencies
	    Map<String, Double> eurRates = new HashMap<>();
	    eurRates.put("USD", 1.10);
	    eurRates.put("INR", 90.12);
	    eurRates.put("GBP", 0.85);
	    eurRates.put("JPY", 160.80);
	    eurRates.put("AUD", 1.64);
	    eurRates.put("CAD", 1.47);
	    eurRates.put("CNY", 7.98);
	    eurRates.put("RUB", 103.22);
	    eurRates.put("BRL", 5.38);
	    eurRates.put("MXN", 18.76);
	    eurRates.put("ZAR", 20.44);
	    eurRates.put("SAR", 4.08);
	    eurRates.put("KRW", 1435.70);
	    eurRates.put("CHF", 0.97);
	    eurRates.put("TRY", 29.71);
	    eurRates.put("SGD", 1.50);
	    eurRates.put("NZD", 1.79);
	    eurRates.put("SEK", 12.10);
	    eurRates.put("NOK", 11.65);
	    eurRates.put("DKK", 7.46);
	    eurRates.put("MYR", 5.07);
	    eurRates.put("THB", 38.75);
	    eurRates.put("IDR", 16857.81);
	    eurRates.put("PHP", 62.40);
	    eurRates.put("NGN", 852.45);
	    eurRates.put("EGP", 34.03);
	    eurRates.put("ARS", 456.89);
	    eurRates.put("CLP", 1147.63);
	    eurRates.put("VND", 31760.50);
	    eurRates.put("PKR", 373.11);
	    eurRates.put("BDT", 142.82);
	    eurRates.put("AED", 4.03);
	    eurRates.put("QAR", 4.00);
	    eurRates.put("ILS", 4.14);
	    exchangeRates.put("EUR", eurRates);

	    // GBP to other currencies
	    Map<String, Double> gbpRates = new HashMap<>();
	    gbpRates.put("USD", 1.30);
	    gbpRates.put("INR", 104.23);
	    gbpRates.put("EUR", 1.18);
	    gbpRates.put("JPY", 189.04);
	    gbpRates.put("AUD", 1.93);
	    gbpRates.put("CAD", 1.73);
	    gbpRates.put("CNY", 9.42);
	    gbpRates.put("RUB", 122.31);
	    gbpRates.put("BRL", 6.37);
	    gbpRates.put("MXN", 22.21);
	    gbpRates.put("ZAR", 24.20);
	    gbpRates.put("SAR", 4.83);
	    gbpRates.put("KRW", 1699.31);
	    gbpRates.put("CHF", 1.15);
	    gbpRates.put("TRY", 35.23);
	    gbpRates.put("SGD", 1.78);
	    gbpRates.put("NZD", 2.12);
	    gbpRates.put("SEK", 14.28);
	    gbpRates.put("NOK", 13.75);
	    gbpRates.put("DKK", 8.81);
	    gbpRates.put("MYR", 5.99);
	    gbpRates.put("THB", 45.77);
	    gbpRates.put("IDR", 19897.03);
	    gbpRates.put("PHP", 73.67);
	    gbpRates.put("NGN", 1005.65);
	    gbpRates.put("EGP", 40.14);
	    gbpRates.put("ARS", 538.25);
	    gbpRates.put("CLP", 1352.67);
	    gbpRates.put("VND", 37442.00);
	    gbpRates.put("PKR", 439.82);
	    gbpRates.put("BDT", 168.48);
	    gbpRates.put("AED", 4.75);
	    gbpRates.put("QAR", 4.71);
	    gbpRates.put("ILS", 4.88);
	    exchangeRates.put("GBP", gbpRates);

	    // JPY to other currencies
	    Map<String, Double> jpyRates = new HashMap<>();
	    jpyRates.put("USD", 0.0068);
	    jpyRates.put("INR", 0.57);
	    jpyRates.put("EUR", 0.0062);
	    jpyRates.put("GBP", 0.0053);
	    jpyRates.put("AUD", 0.0102);
	    jpyRates.put("CAD", 0.0091);
	    jpyRates.put("CNY", 0.050);
	    jpyRates.put("RUB", 0.65);
	    jpyRates.put("BRL", 0.034);
	    jpyRates.put("MXN", 0.12);
	    jpyRates.put("ZAR", 0.13);
	    jpyRates.put("SAR", 0.025);
	    jpyRates.put("KRW", 8.96);
	    jpyRates.put("CHF", 0.0060);
	    jpyRates.put("TRY", 0.18);
	    jpyRates.put("SGD", 0.0090);
	    jpyRates.put("NZD", 0.012);
	    jpyRates.put("SEK", 0.081);
	    jpyRates.put("NOK", 0.079);
	    jpyRates.put("DKK", 0.050);
	    jpyRates.put("MYR", 0.034);
	    jpyRates.put("THB", 0.26);
	    jpyRates.put("IDR", 115.00);
	    jpyRates.put("PHP", 0.42);
	    jpyRates.put("NGN", 5.79);
	    jpyRates.put("EGP", 0.23);
	    jpyRates.put("ARS", 3.10);
	    jpyRates.put("CLP", 7.80);
	    jpyRates.put("VND", 216.85);
	    jpyRates.put("PKR", 2.55);
	    jpyRates.put("BDT", 0.97);
	    jpyRates.put("AED", 0.025);
	    jpyRates.put("QAR", 0.025);
	    jpyRates.put("ILS", 0.026);
	    exchangeRates.put("JPY", jpyRates);

	    // AUD to other currencies
	    Map<String, Double> audRates = new HashMap<>();
	    audRates.put("USD", 0.67);
	    audRates.put("INR", 53.47);
	    audRates.put("EUR", 0.61);
	    audRates.put("GBP", 0.52);
	    audRates.put("JPY", 98.33);
	    audRates.put("CAD", 0.90);
	    audRates.put("CNY", 4.87);
	    audRates.put("RUB", 63.00);
	    audRates.put("BRL", 3.29);
	    audRates.put("MXN", 11.52);
	    audRates.put("ZAR", 12.56);
	    audRates.put("SAR", 2.53);
	    audRates.put("KRW", 887.10);
	    audRates.put("CHF", 0.59);
	    audRates.put("TRY", 18.06);
	    audRates.put("SGD", 0.91);
	    audRates.put("NZD", 1.21);
	    audRates.put("SEK", 5.71);
	    audRates.put("NOK", 5.49);
	    audRates.put("DKK", 3.53);
	    audRates.put("MYR", 2.40);
	    audRates.put("THB", 18.39);
	    audRates.put("IDR", 8025.15);
	    audRates.put("PHP", 29.71);
	    audRates.put("NGN", 409.80);
	    audRates.put("EGP", 16.35);
	    audRates.put("ARS", 219.45);
	    audRates.put("CLP", 551.78);
	    audRates.put("VND", 15337.00);
	    audRates.put("PKR", 180.12);
	    audRates.put("BDT", 68.99);
	    audRates.put("AED", 2.50);
	    audRates.put("QAR", 2.48);
	    audRates.put("ILS", 2.58);
	    exchangeRates.put("AUD", audRates);

	    // CAD to other currencies
	    Map<String, Double> cadRates = new HashMap<>();
	    cadRates.put("USD", 0.75);
	    cadRates.put("INR", 62.75);
	    cadRates.put("EUR", 0.68);
	    cadRates.put("GBP", 0.58);
	    cadRates.put("JPY", 109.49);
	    cadRates.put("AUD", 1.11);
	    cadRates.put("CNY", 5.45);
	    cadRates.put("RUB", 70.71);
	    cadRates.put("BRL", 3.68);
	    cadRates.put("MXN", 12.83);
	    cadRates.put("ZAR", 14.00);
	    cadRates.put("SAR", 2.80);
	    cadRates.put("KRW", 987.11);
	    cadRates.put("CHF", 0.66);
	    cadRates.put("TRY", 20.41);
	    cadRates.put("SGD", 0.85);
	    cadRates.put("NZD", 1.27);
	    cadRates.put("SEK", 7.75);
	    cadRates.put("NOK", 7.47);
	    cadRates.put("DKK", 4.79);
	    cadRates.put("MYR", 3.25);
	    cadRates.put("THB", 24.82);
	    cadRates.put("IDR", 10751.23);
	    cadRates.put("PHP", 39.00);
	    cadRates.put("NGN", 533.60);
	    cadRates.put("EGP", 21.32);
	    cadRates.put("ARS", 285.80);
	    cadRates.put("CLP", 718.68);
	    cadRates.put("VND", 19915.00);
	    cadRates.put("PKR", 233.37);
	    cadRates.put("BDT", 89.45);
	    cadRates.put("AED", 2.75);
	    cadRates.put("QAR", 2.71);
	    cadRates.put("ILS", 2.81);
	    exchangeRates.put("CAD", cadRates);
	    
    	// PKR to other currencies
	    Map<String, Double> pkrRates = new HashMap<>();
	    pkrRates.put("USD", 0.0035);
	    pkrRates.put("INR", 0.30);
	    pkrRates.put("EUR", 0.0027);
	    pkrRates.put("GBP", 0.0023);
	    pkrRates.put("JPY", 0.25);
	    pkrRates.put("AUD", 0.019);
	    pkrRates.put("CAD", 0.015);
	    pkrRates.put("BDT", 0.51);
	    pkrRates.put("CNY", 0.024);
	    pkrRates.put("RUB", 0.36);
	    pkrRates.put("BRL", 0.018);
	    pkrRates.put("MXN", 0.061);
	    pkrRates.put("ZAR", 0.067);
	    pkrRates.put("SAR", 0.013);
	    pkrRates.put("KRW", 4.00);
	    pkrRates.put("CHF", 0.0031);
	    pkrRates.put("TRY", 0.14);
	    pkrRates.put("SGD", 0.0044);
	    pkrRates.put("NZD", 0.0062);
	    pkrRates.put("SEK", 0.048);
	    pkrRates.put("NOK", 0.047);
	    pkrRates.put("DKK", 0.030);
	    pkrRates.put("MYR", 0.020);
	    pkrRates.put("THB", 0.15);
	    pkrRates.put("IDR", 54.00);
	    pkrRates.put("PHP", 0.19);
	    pkrRates.put("NGN", 1.60);
	    pkrRates.put("EGP", 0.06);
	    pkrRates.put("ARS", 1.20);
	    pkrRates.put("CLP", 3.20);
	    pkrRates.put("VND", 8.15);
	    pkrRates.put("BDT", 0.46);
	    pkrRates.put("AED", 0.013);
	    pkrRates.put("QAR", 0.013);
	    pkrRates.put("ILS", 0.013);
	    exchangeRates.put("PKR", pkrRates);

	    // BDT to other currencies
	    Map<String, Double> bdtRates = new HashMap<>();
	    bdtRates.put("USD", 0.0092);
	    bdtRates.put("INR", 0.93);
	    bdtRates.put("EUR", 0.0085);
	    bdtRates.put("GBP", 0.0071);
	    bdtRates.put("JPY", 2.15);
	    bdtRates.put("AUD", 0.016);
	    bdtRates.put("CAD", 0.012);
	    bdtRates.put("PKR", 2.15);
	    bdtRates.put("CNY", 0.065);
	    bdtRates.put("RUB", 1.42);
	    bdtRates.put("BRL", 0.060);
	    bdtRates.put("MXN", 0.28);
	    bdtRates.put("ZAR", 0.28);
	    bdtRates.put("SAR", 0.035);
	    bdtRates.put("KRW", 12.70);
	    bdtRates.put("CHF", 0.0082);
	    bdtRates.put("TRY", 0.36);
	    bdtRates.put("SGD", 0.010);
	    bdtRates.put("NZD", 0.015);
	    bdtRates.put("SEK", 0.13);
	    bdtRates.put("NOK", 0.13);
	    bdtRates.put("DKK", 0.080);
	    bdtRates.put("MYR", 0.051);
	    bdtRates.put("THB", 0.41);
	    bdtRates.put("IDR", 183.25);
	    bdtRates.put("PHP", 0.71);
	    bdtRates.put("NGN", 8.23);
	    bdtRates.put("EGP", 0.37);
	    bdtRates.put("ARS", 4.24);
	    bdtRates.put("CLP", 10.00);
	    bdtRates.put("VND", 290.75);
	    bdtRates.put("AED", 0.037);
	    bdtRates.put("QAR", 0.036);
	    bdtRates.put("ILS", 0.038);
	    exchangeRates.put("BDT", bdtRates);
	    
	    // AED to other currencies
	    Map<String, Double> aedRates = new HashMap<>();
	    aedRates.put("USD", 0.27);
	    aedRates.put("INR", 22.54);
	    aedRates.put("EUR", 0.24);
	    aedRates.put("GBP", 0.21);
	    aedRates.put("JPY", 29.67);
	    aedRates.put("AUD", 0.41);
	    aedRates.put("CAD", 0.35);
	    aedRates.put("PKR", 74.23);
	    aedRates.put("BDT", 28.16);
	    aedRates.put("CNY", 1.83);
	    aedRates.put("RUB", 19.70);
	    aedRates.put("BRL", 1.37);
	    aedRates.put("MXN", 5.06);
	    aedRates.put("ZAR", 4.95);
	    aedRates.put("SAR", 1.02);
	    aedRates.put("KRW", 339.51);
	    aedRates.put("CHF", 0.24);
	    aedRates.put("TRY", 7.51);
	    aedRates.put("SGD", 0.37);
	    aedRates.put("NZD", 0.44);
	    aedRates.put("SEK", 2.71);
	    aedRates.put("NOK", 2.58);
	    aedRates.put("DKK", 1.64);
	    aedRates.put("MYR", 1.16);
	    aedRates.put("THB", 8.89);
	    aedRates.put("IDR", 3000.00);
	    aedRates.put("PHP", 14.95);
	    aedRates.put("NGN", 208.96);
	    aedRates.put("EGP", 8.21);
	    aedRates.put("ARS", 105.76);
	    aedRates.put("CLP", 267.81);
	    aedRates.put("VND", 7554.00);
	    aedRates.put("QAR", 0.98);
	    aedRates.put("ILS", 0.98);
	    exchangeRates.put("AED", aedRates);

	    // SAR to other currencies
	    Map<String, Double> sarRates = new HashMap<>();
	    sarRates.put("USD", 0.27);
	    sarRates.put("INR", 22.24);
	    sarRates.put("EUR", 0.24);
	    sarRates.put("GBP", 0.21);
	    sarRates.put("JPY", 29.34);
	    sarRates.put("AUD", 0.41);
	    sarRates.put("CAD", 0.35);
	    sarRates.put("PKR", 73.23);
	    sarRates.put("BDT", 27.77);
	    sarRates.put("CNY", 1.80);
	    sarRates.put("RUB", 19.45);
	    sarRates.put("BRL", 1.36);
	    sarRates.put("MXN", 4.94);
	    sarRates.put("ZAR", 4.83);
	    sarRates.put("AED", 0.98);
	    sarRates.put("KRW", 335.50);
	    sarRates.put("CHF", 0.24);
	    sarRates.put("TRY", 7.42);
	    sarRates.put("SGD", 0.37);
	    sarRates.put("NZD", 0.44);
	    sarRates.put("SEK", 2.69);
	    sarRates.put("NOK", 2.56);
	    sarRates.put("DKK", 1.62);
	    sarRates.put("MYR", 1.15);
	    sarRates.put("THB", 8.82);
	    sarRates.put("IDR", 2970.00);
	    sarRates.put("PHP", 14.80);
	    sarRates.put("NGN", 207.00);
	    sarRates.put("EGP", 8.14);
	    sarRates.put("ARS", 104.89);
	    sarRates.put("CLP", 265.36);
	    sarRates.put("VND", 7482.00);
	    sarRates.put("QAR", 0.98);
	    sarRates.put("ILS", 0.98);
	    exchangeRates.put("SAR", sarRates);
	    
	    // CNY to other currencies
	    Map<String, Double> cnyRates = new HashMap<>();
	    cnyRates.put("USD", 0.14);
	    cnyRates.put("INR", 11.36);
	    cnyRates.put("EUR", 0.13);
	    cnyRates.put("GBP", 0.11);
	    cnyRates.put("JPY", 20.30);
	    cnyRates.put("AUD", 0.22);
	    cnyRates.put("CAD", 0.19);
	    cnyRates.put("PKR", 41.00);
	    cnyRates.put("BDT", 15.28);
	    cnyRates.put("RUB", 9.25);
	    cnyRates.put("BRL", 0.69);
	    cnyRates.put("MXN", 3.34);
	    cnyRates.put("ZAR", 2.75);
	    cnyRates.put("SAR", 0.53);
	    cnyRates.put("KRW", 196.00);
	    cnyRates.put("CHF", 0.13);
	    cnyRates.put("TRY", 5.89);
	    cnyRates.put("SGD", 0.19);
	    cnyRates.put("NZD", 0.21);
	    cnyRates.put("SEK", 1.47);
	    cnyRates.put("NOK", 1.36);
	    cnyRates.put("DKK", 0.87);
	    cnyRates.put("MYR", 0.66);
	    cnyRates.put("THB", 4.96);
	    cnyRates.put("IDR", 2110.00);
	    cnyRates.put("PHP", 8.24);
	    cnyRates.put("NGN", 110.50);
	    cnyRates.put("EGP", 5.20);
	    cnyRates.put("ARS", 18.75);
	    cnyRates.put("CLP", 39.90);
	    cnyRates.put("VND", 3380.00);
	    cnyRates.put("AED", 0.53);
	    cnyRates.put("QAR", 0.52);
	    cnyRates.put("ILS", 0.52);
	    exchangeRates.put("CNY", cnyRates);

	    // RUB to other currencies
	    Map<String, Double> rubRates = new HashMap<>();
	    rubRates.put("USD", 0.011);
	    rubRates.put("INR", 1.23);
	    rubRates.put("EUR", 0.0099);
	    rubRates.put("GBP", 0.0084);
	    rubRates.put("JPY", 14.10);
	    rubRates.put("AUD", 0.018);
	    rubRates.put("CAD", 0.015);
	    rubRates.put("PKR", 2.21);
	    rubRates.put("BDT", 1.42);
	    rubRates.put("CNY", 0.11);
	    rubRates.put("BRL", 0.073);
	    rubRates.put("MXN", 0.37);
	    rubRates.put("ZAR", 0.31);
	    rubRates.put("SAR", 0.043);
	    rubRates.put("KRW", 21.20);
	    rubRates.put("CHF", 0.0098);
	    rubRates.put("TRY", 0.67);
	    rubRates.put("SGD", 0.013);
	    rubRates.put("NZD", 0.014);
	    rubRates.put("SEK", 0.11);
	    rubRates.put("NOK", 0.11);
	    rubRates.put("DKK", 0.072);
	    rubRates.put("MYR", 0.049);
	    rubRates.put("THB", 0.41);
	    rubRates.put("IDR", 141.50);
	    rubRates.put("PHP", 0.42);
	    rubRates.put("NGN", 8.90);
	    rubRates.put("EGP", 0.37);
	    rubRates.put("ARS", 2.67);
	    rubRates.put("CLP", 9.81);
	    rubRates.put("VND", 213.00);
	    rubRates.put("AED", 0.043);
	    rubRates.put("QAR", 0.042);
	    rubRates.put("ILS", 0.042);
	    exchangeRates.put("RUB", rubRates);

	    // BRL to other currencies
	    Map<String, Double> brlRates = new HashMap<>();
	    brlRates.put("USD", 0.20);
	    brlRates.put("INR", 16.43);
	    brlRates.put("EUR", 0.18);
	    brlRates.put("GBP", 0.15);
	    brlRates.put("JPY", 28.21);
	    brlRates.put("AUD", 0.31);
	    brlRates.put("CAD", 0.27);
	    brlRates.put("PKR", 58.00);
	    brlRates.put("BDT", 22.15);
	    brlRates.put("CNY", 1.45);
	    brlRates.put("RUB", 13.66);
	    brlRates.put("MXN", 5.63);
	    brlRates.put("ZAR", 5.05);
	    brlRates.put("SAR", 0.91);
	    brlRates.put("KRW", 306.25);
	    brlRates.put("CHF", 0.18);
	    brlRates.put("TRY", 6.47);
	    brlRates.put("SGD", 0.26);
	    brlRates.put("NZD", 0.28);
	    brlRates.put("SEK", 2.01);
	    brlRates.put("NOK", 1.90);
	    brlRates.put("DKK", 1.25);
	    brlRates.put("MYR", 0.93);
	    brlRates.put("THB", 7.13);
	    brlRates.put("IDR", 2950.00);
	    brlRates.put("PHP", 15.50);
	    brlRates.put("NGN", 71.25);
	    brlRates.put("EGP", 3.55);
	    brlRates.put("ARS", 47.88);
	    brlRates.put("CLP", 95.62);
	    brlRates.put("VND", 2450.00);
	    brlRates.put("AED", 0.91);
	    brlRates.put("QAR", 0.90);
	    brlRates.put("ILS", 0.90);
	    exchangeRates.put("BRL", brlRates);

	    // MXN to other currencies
	    Map<String, Double> mxnRates = new HashMap<>();
	    mxnRates.put("USD", 0.058);
	    mxnRates.put("INR", 4.83);
	    mxnRates.put("EUR", 0.052);
	    mxnRates.put("GBP", 0.044);
	    mxnRates.put("JPY", 8.31);
	    mxnRates.put("AUD", 0.091);
	    mxnRates.put("CAD", 0.078);
	    mxnRates.put("PKR", 17.00);
	    mxnRates.put("BDT", 6.50);
	    mxnRates.put("CNY", 0.39);
	    mxnRates.put("RUB", 2.71);
	    mxnRates.put("BRL", 0.18);
	    mxnRates.put("ZAR", 0.89);
	    mxnRates.put("SAR", 0.15);
	    mxnRates.put("KRW", 52.50);
	    mxnRates.put("CHF", 0.052);
	    mxnRates.put("TRY", 2.24);
	    mxnRates.put("SGD", 0.067);
	    mxnRates.put("NZD", 0.080);
	    mxnRates.put("SEK", 0.58);
	    mxnRates.put("NOK", 0.53);
	    mxnRates.put("DKK", 0.35);
	    mxnRates.put("MYR", 0.26);
	    mxnRates.put("THB", 1.95);
	    mxnRates.put("IDR", 797.00);
	    mxnRates.put("PHP", 2.35);
	    mxnRates.put("NGN", 20.00);
	    mxnRates.put("EGP", 0.80);
	    mxnRates.put("ARS", 10.32);
	    mxnRates.put("CLP", 26.12);
	    mxnRates.put("VND", 1270.00);
	    mxnRates.put("AED", 0.15);
	    mxnRates.put("QAR", 0.14);
	    mxnRates.put("ILS", 0.14);
	    exchangeRates.put("MXN", mxnRates);
	    
	 // ZAR to other currencies
	    Map<String, Double> zarRates = new HashMap<>();
	    zarRates.put("USD", 0.053);
	    zarRates.put("INR", 4.56);
	    zarRates.put("EUR", 0.048);
	    zarRates.put("GBP", 0.041);
	    zarRates.put("JPY", 8.04);
	    zarRates.put("AUD", 0.085);
	    zarRates.put("CAD", 0.072);
	    zarRates.put("PKR", 14.95);
	    zarRates.put("BDT", 5.90);
	    zarRates.put("CNY", 0.36);
	    zarRates.put("RUB", 3.24);
	    zarRates.put("BRL", 0.20);
	    zarRates.put("MXN", 1.12);
	    zarRates.put("SAR", 0.21);
	    zarRates.put("KRW", 57.60);
	    zarRates.put("CHF", 0.049);
	    zarRates.put("TRY", 2.30);
	    zarRates.put("SGD", 0.072);
	    zarRates.put("NZD", 0.086);
	    zarRates.put("SEK", 0.62);
	    zarRates.put("NOK", 0.58);
	    zarRates.put("DKK", 0.40);
	    zarRates.put("MYR", 0.30);
	    zarRates.put("THB", 2.35);
	    zarRates.put("IDR", 9780.00);
	    zarRates.put("PHP", 4.25);
	    zarRates.put("NGN", 27.50);
	    zarRates.put("EGP", 1.14);
	    zarRates.put("ARS", 14.20);
	    zarRates.put("CLP", 31.10);
	    zarRates.put("VND", 2720.00);
	    zarRates.put("AED", 0.21);
	    zarRates.put("QAR", 0.20);
	    zarRates.put("ILS", 0.20);
	    exchangeRates.put("ZAR", zarRates);

	    // KRW to other currencies
	    Map<String, Double> krwRates = new HashMap<>();
	    krwRates.put("USD", 0.00075);
	    krwRates.put("INR", 0.063);
	    krwRates.put("EUR", 0.00069);
	    krwRates.put("GBP", 0.00059);
	    krwRates.put("JPY", 0.11);
	    krwRates.put("AUD", 0.0011);
	    krwRates.put("CAD", 0.00095);
	    krwRates.put("PKR", 0.25);
	    krwRates.put("BDT", 0.09);
	    krwRates.put("CNY", 0.0051);
	    krwRates.put("RUB", 0.047);
	    krwRates.put("BRL", 0.0032);
	    krwRates.put("MXN", 0.019);
	    krwRates.put("ZAR", 0.017);
	    krwRates.put("SAR", 0.0031);
	    krwRates.put("CHF", 0.00073);
	    krwRates.put("TRY", 0.031);
	    krwRates.put("SGD", 0.00097);
	    krwRates.put("NZD", 0.0011);
	    krwRates.put("SEK", 0.0058);
	    krwRates.put("NOK", 0.0054);
	    krwRates.put("DKK", 0.0039);
	    krwRates.put("MYR", 0.0028);
	    krwRates.put("THB", 0.021);
	    krwRates.put("IDR", 1060.00);
	    krwRates.put("PHP", 0.060);
	    krwRates.put("NGN", 0.44);
	    krwRates.put("EGP", 0.018);
	    krwRates.put("ARS", 0.72);
	    krwRates.put("CLP", 1.63);
	    krwRates.put("VND", 14.10);
	    krwRates.put("AED", 0.0031);
	    krwRates.put("QAR", 0.0030);
	    krwRates.put("ILS", 0.0031);
	    exchangeRates.put("KRW", krwRates);

	    // CHF to other currencies
	    Map<String, Double> chfRates = new HashMap<>();
	    chfRates.put("USD", 1.10);
	    chfRates.put("INR", 91.50);
	    chfRates.put("EUR", 0.93);
	    chfRates.put("GBP", 0.77);
	    chfRates.put("JPY", 145.60);
	    chfRates.put("AUD", 1.50);
	    chfRates.put("CAD", 1.34);
	    chfRates.put("PKR", 321.00);
	    chfRates.put("BDT", 114.00);
	    chfRates.put("CNY", 6.90);
	    chfRates.put("RUB", 102.00);
	    chfRates.put("BRL", 5.30);
	    chfRates.put("MXN", 19.20);
	    chfRates.put("ZAR", 20.50);
	    chfRates.put("SAR", 4.10);
	    chfRates.put("KRW", 1360.00);
	    chfRates.put("TRY", 20.00);
	    chfRates.put("SGD", 1.45);
	    chfRates.put("NZD", 1.60);
	    chfRates.put("SEK", 11.70);
	    chfRates.put("NOK", 11.10);
	    chfRates.put("DKK", 7.60);
	    chfRates.put("MYR", 5.50);
	    chfRates.put("THB", 40.00);
	    chfRates.put("IDR", 2290.00);
	    chfRates.put("PHP", 56.00);
	    chfRates.put("NGN", 448.00);
	    chfRates.put("EGP", 19.00);
	    chfRates.put("ARS", 95.00);
	    chfRates.put("CLP", 2580.00);
	    chfRates.put("VND", 25800.00);
	    chfRates.put("AED", 4.10);
	    chfRates.put("QAR", 4.00);
	    chfRates.put("ILS", 4.00);
	    exchangeRates.put("CHF", chfRates);

	    // TRY to other currencies
	    Map<String, Double> tryRates = new HashMap<>();
	    tryRates.put("USD", 0.037);
	    tryRates.put("INR", 3.06);
	    tryRates.put("EUR", 0.032);
	    tryRates.put("GBP", 0.027);
	    tryRates.put("JPY", 5.06);
	    tryRates.put("AUD", 0.055);
	    tryRates.put("CAD", 0.048);
	    tryRates.put("PKR", 7.14);
	    tryRates.put("BDT", 2.68);
	    tryRates.put("CNY", 0.20);
	    tryRates.put("RUB", 1.49);
	    tryRates.put("BRL", 0.15);
	    tryRates.put("MXN", 0.10);
	    tryRates.put("ZAR", 0.15);
	    tryRates.put("SAR", 0.024);
	    tryRates.put("KRW", 32.00);
	    tryRates.put("CHF", 0.050);
	    tryRates.put("SGD", 0.053);
	    tryRates.put("NZD", 0.060);
	    tryRates.put("SEK", 0.42);
	    tryRates.put("NOK", 0.39);
	    tryRates.put("DKK", 0.26);
	    tryRates.put("MYR", 0.20);
	    tryRates.put("THB", 1.63);
	    tryRates.put("IDR", 695.00);
	    tryRates.put("PHP", 2.55);
	    tryRates.put("NGN", 17.00);
	    tryRates.put("EGP", 0.71);
	    tryRates.put("ARS", 8.40);
	    tryRates.put("CLP", 20.10);
	    tryRates.put("VND", 1860.00);
	    tryRates.put("AED", 0.025);
	    tryRates.put("QAR", 0.024);
	    tryRates.put("ILS", 0.025);
	    exchangeRates.put("TRY", tryRates);

	    // SGD to other currencies
	    Map<String, Double> sgdRates = new HashMap<>();
	    sgdRates.put("USD", 0.73);
	    sgdRates.put("INR", 60.10);
	    sgdRates.put("EUR", 0.67);
	    sgdRates.put("GBP", 0.56);
	    sgdRates.put("JPY", 98.80);
	    sgdRates.put("AUD", 1.08);
	    sgdRates.put("CAD", 0.97);
	    sgdRates.put("PKR", 134.00);
	    sgdRates.put("BDT", 49.00);
	    sgdRates.put("CNY", 5.30);
	    sgdRates.put("RUB", 6.80);
	    sgdRates.put("BRL", 3.80);
	    sgdRates.put("MXN", 15.00);
	    sgdRates.put("ZAR", 13.70);
	    sgdRates.put("SAR", 2.70);
	    sgdRates.put("KRW", 1490.00);
	    sgdRates.put("CHF", 0.69);
	    sgdRates.put("TRY", 18.80);
	    sgdRates.put("NZD", 1.16);
	    sgdRates.put("SEK", 8.40);
	    sgdRates.put("NOK", 8.00);
	    sgdRates.put("DKK", 5.50);
	    sgdRates.put("MYR", 3.90);
	    sgdRates.put("THB", 26.00);
	    sgdRates.put("IDR", 18450.00);
	    sgdRates.put("PHP", 27.00);
	    sgdRates.put("NGN", 188.00);
	    sgdRates.put("EGP", 8.00);
	    sgdRates.put("ARS", 43.00);
	    sgdRates.put("CLP", 1060.00);
	    sgdRates.put("VND", 12200.00);
	    sgdRates.put("AED", 2.70);
	    sgdRates.put("QAR", 2.60);
	    sgdRates.put("ILS", 2.60);
	    exchangeRates.put("SGD", sgdRates);

	    // NZD to other currencies
	    Map<String, Double> nzdRates = new HashMap<>();
	    nzdRates.put("USD", 0.63);
	    nzdRates.put("INR", 52.75);
	    nzdRates.put("EUR", 0.58);
	    nzdRates.put("GBP", 0.49);
	    nzdRates.put("JPY", 87.00);
	    nzdRates.put("AUD", 1.04);
	    nzdRates.put("CAD", 0.90);
	    nzdRates.put("PKR", 115.00);
	    nzdRates.put("BDT", 43.00);
	    nzdRates.put("CNY", 4.75);
	    nzdRates.put("RUB", 4.50);
	    nzdRates.put("BRL", 3.60);
	    nzdRates.put("MXN", 12.30);
	    nzdRates.put("ZAR", 11.60);
	    nzdRates.put("SAR", 2.35);
	    nzdRates.put("KRW", 1130.00);
	    nzdRates.put("CHF", 0.62);
	    nzdRates.put("TRY", 16.30);
	    nzdRates.put("SGD", 0.93);
	    nzdRates.put("SEK", 8.00);
	    nzdRates.put("NOK", 7.50);
	    nzdRates.put("DKK", 5.20);
	    nzdRates.put("MYR", 3.90);
	    nzdRates.put("THB", 23.00);
	    nzdRates.put("IDR", 13800.00);
	    nzdRates.put("PHP", 27.50);
	    nzdRates.put("NGN", 164.00);
	    nzdRates.put("EGP", 7.20);
	    nzdRates.put("ARS", 35.00);
	    nzdRates.put("CLP", 780.00);
	    nzdRates.put("VND", 9500.00);
	    nzdRates.put("AED", 2.35);
	    nzdRates.put("QAR", 2.30);
	    nzdRates.put("ILS", 2.30);
	    exchangeRates.put("NZD", nzdRates);

	    // SEK to other currencies
	    Map<String, Double> sekRates = new HashMap<>();
	    sekRates.put("USD", 0.092);
	    sekRates.put("INR", 7.75);
	    sekRates.put("EUR", 0.087);
	    sekRates.put("GBP", 0.073);
	    sekRates.put("JPY", 13.20);
	    sekRates.put("AUD", 0.12);
	    sekRates.put("CAD", 0.10);
	    sekRates.put("PKR", 18.00);
	    sekRates.put("BDT", 6.80);
	    sekRates.put("CNY", 0.60);
	    sekRates.put("RUB", 6.50);
	    sekRates.put("BRL", 0.31);
	    sekRates.put("MXN", 1.15);
	    sekRates.put("ZAR", 1.60);
	    sekRates.put("SAR", 0.30);
	    sekRates.put("KRW", 172.00);
	    sekRates.put("CHF", 0.087);
	    sekRates.put("TRY", 4.20);
	    sekRates.put("SGD", 0.12);
	    sekRates.put("NZD", 0.13);
	    sekRates.put("NOK", 0.95);
	    sekRates.put("DKK", 0.68);
	    sekRates.put("MYR", 0.50);
	    sekRates.put("THB", 3.40);
	    sekRates.put("IDR", 1460.00);
	    sekRates.put("PHP", 7.10);
	    sekRates.put("NGN", 49.00);
	    sekRates.put("EGP", 2.10);
	    sekRates.put("ARS", 10.80);
	    sekRates.put("CLP", 25.20);
	    sekRates.put("VND", 2360.00);
	    sekRates.put("AED", 0.30);
	    sekRates.put("QAR", 0.29);
	    sekRates.put("ILS", 0.29);
	    exchangeRates.put("SEK", sekRates);

	    // NOK to other currencies
	    Map<String, Double> nokRates = new HashMap<>();
	    nokRates.put("USD", 0.090);
	    nokRates.put("INR", 7.60);
	    nokRates.put("EUR", 0.085);
	    nokRates.put("GBP", 0.070);
	    nokRates.put("JPY", 12.80);
	    nokRates.put("AUD", 0.12);
	    nokRates.put("CAD", 0.10);
	    nokRates.put("PKR", 17.50);
	    nokRates.put("BDT", 6.60);
	    nokRates.put("CNY", 0.58);
	    nokRates.put("RUB", 6.20);
	    nokRates.put("BRL", 0.30);
	    nokRates.put("MXN", 1.10);
	    nokRates.put("ZAR", 1.55);
	    nokRates.put("SAR", 0.29);
	    nokRates.put("KRW", 165.00);
	    nokRates.put("CHF", 0.085);
	    nokRates.put("TRY", 4.10);
	    nokRates.put("SGD", 0.12);
	    nokRates.put("NZD", 0.13);
	    nokRates.put("SEK", 1.05);
	    nokRates.put("DKK", 0.70);
	    nokRates.put("MYR", 0.50);
	    nokRates.put("THB", 3.20);
	    nokRates.put("IDR", 1400.00);
	    nokRates.put("PHP", 6.90);
	    nokRates.put("NGN", 47.00);
	    nokRates.put("EGP", 2.00);
	    nokRates.put("ARS", 10.50);
	    nokRates.put("CLP", 24.00);
	    nokRates.put("VND", 2300.00);
	    nokRates.put("AED", 0.29);
	    nokRates.put("QAR", 0.28);
	    nokRates.put("ILS", 0.28);
	    exchangeRates.put("NOK", nokRates);

	    // DKK to other currencies
	    Map<String, Double> dkkRates = new HashMap<>();
	    dkkRates.put("USD", 0.14);
	    dkkRates.put("INR", 11.00);
	    dkkRates.put("EUR", 0.13);
	    dkkRates.put("GBP", 0.11);
	    dkkRates.put("JPY", 20.70);
	    dkkRates.put("AUD", 0.23);
	    dkkRates.put("CAD", 0.19);
	    dkkRates.put("PKR", 41.50);
	    dkkRates.put("BDT", 15.50);
	    dkkRates.put("CNY", 1.50);
	    dkkRates.put("RUB", 13.00);
	    dkkRates.put("BRL", 0.70);
	    dkkRates.put("MXN", 2.60);
	    dkkRates.put("ZAR", 2.40);
	    dkkRates.put("SAR", 0.45);
	    dkkRates.put("KRW", 320.00);
	    dkkRates.put("CHF", 0.14);
	    dkkRates.put("TRY", 6.40);
	    dkkRates.put("SGD", 0.23);
	    dkkRates.put("NZD", 0.25);
	    dkkRates.put("SEK", 0.95);
	    dkkRates.put("NOK", 1.40);
	    dkkRates.put("MYR", 0.70);
	    dkkRates.put("THB", 4.60);
	    dkkRates.put("IDR", 1950.00);
	    dkkRates.put("PHP", 9.00);
	    dkkRates.put("NGN", 63.00);
	    dkkRates.put("EGP", 2.60);
	    dkkRates.put("ARS", 12.50);
	    dkkRates.put("CLP", 31.00);
	    dkkRates.put("VND", 2780.00);
	    dkkRates.put("AED", 0.45);
	    dkkRates.put("QAR", 0.44);
	    dkkRates.put("ILS", 0.44);
	    exchangeRates.put("DKK", dkkRates);

	    // MYR to other currencies
	    Map<String, Double> myrRates = new HashMap<>();
	    myrRates.put("USD", 0.23);
	    myrRates.put("INR", 18.50);
	    myrRates.put("EUR", 0.21);
	    myrRates.put("GBP", 0.18);
	    myrRates.put("JPY", 32.40);
	    myrRates.put("AUD", 0.35);
	    myrRates.put("CAD", 0.30);
	    myrRates.put("PKR", 37.00);
	    myrRates.put("BDT", 14.00);
	    myrRates.put("CNY", 1.25);
	    myrRates.put("RUB", 11.50);
	    myrRates.put("BRL", 0.70);
	    myrRates.put("MXN", 2.60);
	    myrRates.put("ZAR", 2.50);
	    myrRates.put("SAR", 0.48);
	    myrRates.put("KRW", 270.00);
	    myrRates.put("CHF", 0.22);
	    myrRates.put("TRY", 7.80);
	    myrRates.put("SGD", 0.35);
	    myrRates.put("NZD", 0.37);
	    myrRates.put("SEK", 1.90);
	    myrRates.put("NOK", 1.80);
	    myrRates.put("DKK", 1.30);
	    myrRates.put("THB", 7.10);
	    myrRates.put("IDR", 3500.00);
	    myrRates.put("PHP", 12.50);
	    myrRates.put("NGN", 88.00);
	    myrRates.put("EGP", 3.60);
	    myrRates.put("ARS", 19.00);
	    myrRates.put("CLP", 45.00);
	    myrRates.put("VND", 4200.00);
	    myrRates.put("AED", 0.48);
	    myrRates.put("QAR", 0.46);
	    myrRates.put("ILS", 0.46);
	    exchangeRates.put("MYR", myrRates);

	    // THB to other currencies
	    Map<String, Double> thbRates = new HashMap<>();
	    thbRates.put("USD", 0.030);
	    thbRates.put("INR", 2.50);
	    thbRates.put("EUR", 0.027);
	    thbRates.put("GBP", 0.023);
	    thbRates.put("JPY", 4.20);
	    thbRates.put("AUD", 0.043);
	    thbRates.put("CAD", 0.037);
	    thbRates.put("PKR", 7.00);
	    thbRates.put("BDT", 2.60);
	    thbRates.put("CNY", 0.18);
	    thbRates.put("RUB", 1.70);
	    thbRates.put("BRL", 0.10);
	    thbRates.put("MXN", 0.60);
	    thbRates.put("ZAR", 0.50);
	    thbRates.put("SAR", 0.10);
	    thbRates.put("KRW", 54.00);
	    thbRates.put("CHF", 0.027);
	    thbRates.put("TRY", 1.60);
	    thbRates.put("SGD", 0.043);
	    thbRates.put("NZD", 0.045);
	    thbRates.put("SEK", 0.28);
	    thbRates.put("NOK", 0.26);
	    thbRates.put("DKK", 0.18);
	    thbRates.put("MYR", 0.14);
	    thbRates.put("IDR", 7200.00);
	    thbRates.put("PHP", 3.00);
	    thbRates.put("NGN", 22.00);
	    thbRates.put("EGP", 1.00);
	    thbRates.put("ARS", 5.30);
	    thbRates.put("CLP", 12.00);
	    thbRates.put("VND", 11500.00);
	    thbRates.put("AED", 0.10);
	    thbRates.put("QAR", 0.10);
	    thbRates.put("ILS", 0.10);
	    exchangeRates.put("THB", thbRates);

	    // IDR to other currencies
	    Map<String, Double> idrRates = new HashMap<>();
	    idrRates.put("USD", 0.000065);
	    idrRates.put("INR", 0.0055);
	    idrRates.put("EUR", 0.000060);
	    idrRates.put("GBP", 0.000050);
	    idrRates.put("JPY", 0.0090);
	    idrRates.put("AUD", 0.00010);
	    idrRates.put("CAD", 0.000085);
	    idrRates.put("PKR", 0.017);
	    idrRates.put("BDT", 0.0068);
	    idrRates.put("CNY", 0.00050);
	    idrRates.put("RUB", 0.0046);
	    idrRates.put("BRL", 0.00028);
	    idrRates.put("MXN", 0.0016);
	    idrRates.put("ZAR", 0.0014);
	    idrRates.put("SAR", 0.00028);
	    idrRates.put("KRW", 1.40);
	    idrRates.put("CHF", 0.000060);
	    idrRates.put("TRY", 0.0036);
	    idrRates.put("SGD", 0.00010);
	    idrRates.put("NZD", 0.00011);
	    idrRates.put("SEK", 0.00073);
	    idrRates.put("NOK", 0.00068);
	    idrRates.put("DKK", 0.00048);
	    idrRates.put("MYR", 0.00028);
	    idrRates.put("THB", 0.00014);
	    idrRates.put("PHP", 0.00090);
	    idrRates.put("NGN", 0.0056);
	    idrRates.put("EGP", 0.00022);
	    idrRates.put("ARS", 0.0011);
	    idrRates.put("CLP", 0.0026);
	    idrRates.put("VND", 0.22);
	    idrRates.put("AED", 0.00028);
	    idrRates.put("QAR", 0.00027);
	    idrRates.put("ILS", 0.00027);
	    exchangeRates.put("IDR", idrRates);

	    // PHP to other currencies
	    Map<String, Double> phpRates = new HashMap<>();
	    phpRates.put("USD", 0.018);
	    phpRates.put("INR", 1.50);
	    phpRates.put("EUR", 0.016);
	    phpRates.put("GBP", 0.013);
	    phpRates.put("JPY", 2.30);
	    phpRates.put("AUD", 0.026);
	    phpRates.put("CAD", 0.022);
	    phpRates.put("PKR", 3.60);
	    phpRates.put("BDT", 1.35);
	    phpRates.put("CNY", 0.12);
	    phpRates.put("RUB", 1.00);
	    phpRates.put("BRL", 0.060);
	    phpRates.put("MXN", 0.35);
	    phpRates.put("ZAR", 0.30);
	    phpRates.put("SAR", 0.060);
	    phpRates.put("KRW", 31.00);
	    phpRates.put("CHF", 0.016);
	    phpRates.put("TRY", 1.10);
	    phpRates.put("SGD", 0.026);
	    phpRates.put("NZD", 0.027);
	    phpRates.put("SEK", 0.13);
	    phpRates.put("NOK", 0.12);
	    phpRates.put("DKK", 0.085);
	    phpRates.put("MYR", 0.080);
	    phpRates.put("THB", 0.33);
	    phpRates.put("IDR", 1.10);
	    phpRates.put("NGN", 0.67);
	    phpRates.put("EGP", 0.030);
	    phpRates.put("ARS", 1.50);
	    phpRates.put("CLP", 3.50);
	    phpRates.put("VND", 35.00);
	    phpRates.put("AED", 0.060);
	    phpRates.put("QAR", 0.059);
	    phpRates.put("ILS", 0.059);
	    exchangeRates.put("PHP", phpRates);

	    // NGN to other currencies
	    Map<String, Double> ngnRates = new HashMap<>();
	    ngnRates.put("USD", 0.0022);
	    ngnRates.put("INR", 0.18);
	    ngnRates.put("EUR", 0.0021);
	    ngnRates.put("GBP", 0.0018);
	    ngnRates.put("JPY", 0.30);
	    ngnRates.put("AUD", 0.0030);
	    ngnRates.put("CAD", 0.0026);
	    ngnRates.put("PKR", 0.37);
	    ngnRates.put("BDT", 0.14);
	    ngnRates.put("CNY", 0.0019);
	    ngnRates.put("RUB", 0.017);
	    ngnRates.put("BRL", 0.010);
	    ngnRates.put("MXN", 0.060);
	    ngnRates.put("ZAR", 0.050);
	    ngnRates.put("SAR", 0.010);
	    ngnRates.put("KRW", 5.40);
	    ngnRates.put("CHF", 0.0021);
	    ngnRates.put("TRY", 0.18);
	    ngnRates.put("SGD", 0.0030);
	    ngnRates.put("NZD", 0.0032);
	    ngnRates.put("SEK", 0.018);
	    ngnRates.put("NOK", 0.017);
	    ngnRates.put("DKK", 0.012);
	    ngnRates.put("MYR", 0.011);
	    ngnRates.put("THB", 0.045);
	    ngnRates.put("IDR", 0.18);
	    ngnRates.put("PHP", 1.50);
	    ngnRates.put("EGP", 0.080);
	    ngnRates.put("ARS", 0.36);
	    ngnRates.put("CLP", 0.85);
	    ngnRates.put("VND", 8.20);
	    ngnRates.put("AED", 0.010);
	    ngnRates.put("QAR", 0.010);
	    ngnRates.put("ILS", 0.010);
	    exchangeRates.put("NGN", ngnRates);

	    // EGP to other currencies
	    Map<String, Double> egpRates = new HashMap<>();
	    egpRates.put("USD", 0.032);
	    egpRates.put("INR", 2.70);
	    egpRates.put("EUR", 0.030);
	    egpRates.put("GBP", 0.025);
	    egpRates.put("JPY", 4.50);
	    egpRates.put("AUD", 0.047);
	    egpRates.put("CAD", 0.040);
	    egpRates.put("PKR", 7.00);
	    egpRates.put("BDT", 2.60);
	    egpRates.put("CNY", 0.20);
	    egpRates.put("RUB", 1.80);
	    egpRates.put("BRL", 0.11);
	    egpRates.put("MXN", 0.070);
	    egpRates.put("ZAR", 0.060);
	    egpRates.put("SAR", 0.012);
	    egpRates.put("KRW", 55.00);
	    egpRates.put("CHF", 0.030);
	    egpRates.put("TRY", 1.60);
	    egpRates.put("SGD", 0.047);
	    egpRates.put("NZD", 0.050);
	    egpRates.put("SEK", 0.21);
	    egpRates.put("NOK", 0.20);
	    egpRates.put("DKK", 0.14);
	    egpRates.put("MYR", 0.11);
	    egpRates.put("THB", 1.00);
	    egpRates.put("IDR", 4.50);
	    egpRates.put("PHP", 0.030);
	    egpRates.put("NGN", 0.080);
	    egpRates.put("ARS", 2.00);
	    egpRates.put("CLP", 5.00);
	    egpRates.put("VND", 50.00);
	    egpRates.put("AED", 0.012);
	    egpRates.put("QAR", 0.012);
	    egpRates.put("ILS", 0.012);
	    exchangeRates.put("EGP", egpRates);

	    // ARS to other currencies
	    Map<String, Double> arsRates = new HashMap<>();
	    arsRates.put("USD", 0.0035);
	    arsRates.put("INR", 0.29);
	    arsRates.put("EUR", 0.0033);
	    arsRates.put("GBP", 0.0028);
	    arsRates.put("JPY", 0.57);
	    arsRates.put("AUD", 0.0060);
	    arsRates.put("CAD", 0.0052);
	    arsRates.put("PKR", 0.93);
	    arsRates.put("BDT", 0.35);
	    arsRates.put("CNY", 0.027);
	    arsRates.put("RUB", 0.22);
	    arsRates.put("BRL", 0.015);
	    arsRates.put("MXN", 0.09);
	    arsRates.put("ZAR", 0.075);
	    arsRates.put("SAR", 0.015);
	    arsRates.put("KRW", 7.70);
	    arsRates.put("CHF", 0.0033);
	    arsRates.put("TRY", 0.27);
	    arsRates.put("SGD", 0.0060);
	    arsRates.put("NZD", 0.0063);
	    arsRates.put("SEK", 0.027);
	    arsRates.put("NOK", 0.025);
	    arsRates.put("DKK", 0.018);
	    arsRates.put("MYR", 0.015);
	    arsRates.put("THB", 0.080);
	    arsRates.put("IDR", 0.12);
	    arsRates.put("PHP", 0.67);
	    arsRates.put("NGN", 0.36);
	    arsRates.put("EGP", 0.50);
	    arsRates.put("CLP", 1.20);
	    arsRates.put("VND", 12.00);
	    arsRates.put("AED", 0.015);
	    arsRates.put("QAR", 0.015);
	    arsRates.put("ILS", 0.015);
	    exchangeRates.put("ARS", arsRates);

	    // CLP to other currencies
	    Map<String, Double> clpRates = new HashMap<>();
	    clpRates.put("USD", 0.0012);
	    clpRates.put("INR", 0.10);
	    clpRates.put("EUR", 0.0011);
	    clpRates.put("GBP", 0.00095);
	    clpRates.put("JPY", 0.18);
	    clpRates.put("AUD", 0.0020);
	    clpRates.put("CAD", 0.0018);
	    clpRates.put("PKR", 0.36);
	    clpRates.put("BDT", 0.14);
	    clpRates.put("CNY", 0.010);
	    clpRates.put("RUB", 0.090);
	    clpRates.put("BRL", 0.0060);
	    clpRates.put("MXN", 0.040);
	    clpRates.put("ZAR", 0.035);
	    clpRates.put("SAR", 0.0070);
	    clpRates.put("KRW", 3.10);
	    clpRates.put("CHF", 0.0011);
	    clpRates.put("TRY", 0.085);
	    clpRates.put("SGD", 0.0020);
	    clpRates.put("NZD", 0.0021);
	    clpRates.put("SEK", 0.012);
	    clpRates.put("NOK", 0.011);
	    clpRates.put("DKK", 0.0080);
	    clpRates.put("MYR", 0.0060);
	    clpRates.put("THB", 0.12);
	    clpRates.put("IDR", 0.50);
	    clpRates.put("PHP", 0.35);
	    clpRates.put("NGN", 0.085);
	    clpRates.put("EGP", 0.20);
	    clpRates.put("ARS", 0.83);
	    clpRates.put("VND", 10.00);
	    clpRates.put("AED", 0.0070);
	    clpRates.put("QAR", 0.0070);
	    clpRates.put("ILS", 0.0070);
	    exchangeRates.put("CLP", clpRates);

	    // VND to other currencies
	    Map<String, Double> vndRates = new HashMap<>();
	    vndRates.put("USD", 0.000042);
	    vndRates.put("INR", 0.0035);
	    vndRates.put("EUR", 0.000040);
	    vndRates.put("GBP", 0.000035);
	    vndRates.put("JPY", 0.0070);
	    vndRates.put("AUD", 0.000047);
	    vndRates.put("CAD", 0.000040);
	    vndRates.put("PKR", 0.0070);
	    vndRates.put("BDT", 0.0027);
	    vndRates.put("CNY", 0.00031);
	    vndRates.put("RUB", 0.0028);
	    vndRates.put("BRL", 0.00018);
	    vndRates.put("MXN", 0.0010);
	    vndRates.put("ZAR", 0.00085);
	    vndRates.put("SAR", 0.00018);
	    vndRates.put("KRW", 0.95);
	    vndRates.put("CHF", 0.000040);
	    vndRates.put("TRY", 0.0030);
	    vndRates.put("SGD", 0.000047);
	    vndRates.put("NZD", 0.000050);
	    vndRates.put("SEK", 0.00030);
	    vndRates.put("NOK", 0.00028);
	    vndRates.put("DKK", 0.00020);
	    vndRates.put("MYR", 0.00018);
	    vndRates.put("THB", 0.000087);
	    vndRates.put("IDR", 0.0046);
	    vndRates.put("PHP", 0.028);
	    vndRates.put("NGN", 0.00012);
	    vndRates.put("EGP", 0.020);
	    vndRates.put("ARS", 0.083);
	    vndRates.put("CLP", 0.10);
	    vndRates.put("AED", 0.00018);
	    vndRates.put("QAR", 0.00018);
	    vndRates.put("ILS", 0.00018);
	    exchangeRates.put("VND", vndRates);

	    // QAR to other currencies
	    Map<String, Double> qarRates = new HashMap<>();
	    qarRates.put("USD", 0.27);
	    qarRates.put("INR", 22.00);
	    qarRates.put("EUR", 0.24);
	    qarRates.put("GBP", 0.20);
	    qarRates.put("JPY", 35.00);
	    qarRates.put("AUD", 0.39);
	    qarRates.put("CAD", 0.33);
	    qarRates.put("PKR", 39.00);
	    qarRates.put("BDT", 15.00);
	    qarRates.put("CNY", 1.20);
	    qarRates.put("RUB", 11.00);
	    qarRates.put("BRL", 0.73);
	    qarRates.put("MXN", 2.80);
	    qarRates.put("ZAR", 2.60);
	    qarRates.put("SAR", 0.53);
	    qarRates.put("KRW", 370.00);
	    qarRates.put("CHF", 0.27);
	    qarRates.put("TRY", 10.00);
	    qarRates.put("SGD", 0.39);
	    qarRates.put("NZD", 0.41);
	    qarRates.put("SEK", 2.70);
	    qarRates.put("NOK", 2.50);
	    qarRates.put("DKK", 1.80);
	    qarRates.put("MYR", 1.40);
	    qarRates.put("THB", 10.00);
	    qarRates.put("IDR", 4400.00);
	    qarRates.put("PHP", 22.00);
	    qarRates.put("NGN", 1.60);
	    qarRates.put("EGP", 0.53);
	    qarRates.put("ARS", 7.00);
	    qarRates.put("CLP", 17.00);
	    qarRates.put("VND", 18500.00);
	    qarRates.put("AED", 1.00);
	    qarRates.put("ILS", 1.00);
	    exchangeRates.put("QAR", qarRates);

	    // ILS to other currencies
	    Map<String, Double> ilsRates = new HashMap<>();
	    ilsRates.put("USD", 0.27);
	    ilsRates.put("INR", 22.00);
	    ilsRates.put("EUR", 0.24);
	    ilsRates.put("GBP", 0.20);
	    ilsRates.put("JPY", 35.00);
	    ilsRates.put("AUD", 0.39);
	    ilsRates.put("CAD", 0.33);
	    ilsRates.put("PKR", 39.00);
	    ilsRates.put("BDT", 15.00);
	    ilsRates.put("CNY", 1.20);
	    ilsRates.put("RUB", 11.00);
	    ilsRates.put("BRL", 0.73);
	    ilsRates.put("MXN", 2.80);
	    ilsRates.put("ZAR", 2.60);
	    ilsRates.put("SAR", 0.53);
	    ilsRates.put("KRW", 370.00);
	    ilsRates.put("CHF", 0.27);
	    ilsRates.put("TRY", 10.00);
	    ilsRates.put("SGD", 0.39);
	    ilsRates.put("NZD", 0.41);
	    ilsRates.put("SEK", 2.70);
	    ilsRates.put("NOK", 2.50);
	    ilsRates.put("DKK", 1.80);
	    ilsRates.put("MYR", 1.40);
	    ilsRates.put("THB", 10.00);
	    ilsRates.put("IDR", 4400.00);
	    ilsRates.put("PHP", 22.00);
	    ilsRates.put("NGN", 1.60);
	    ilsRates.put("EGP", 0.53);
	    ilsRates.put("ARS", 7.00);
	    ilsRates.put("CLP", 17.00);
	    ilsRates.put("VND", 18500.00);
	    ilsRates.put("AED", 1.00);
	    ilsRates.put("QAR", 1.00);
	    exchangeRates.put("ILS", ilsRates);
	}
}

